version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install serverless -g
      - npm install
  build:
    commands:
      - cd service-1
      - sls deploy -s dev
      - cd ../service-2
      - sls deploy -s dev
artifacts:
  files:
    - '**/*'
  base-directory: .serverless