service: serverless-nodejs-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  versionFunctions: true
  package: # Optional deployment packaging configuration
    individually: true

functions:
  getMsg:
    handler: service-1.handler.api
    events:
      - http: GET /
  putMsg:
    handler: service-2.handler.api
    events:
      - http: GET /    
