service: serverless-nodejs-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  versionFunctions: true
  package: # Optional deployment packaging configuration
    individually: true

functions:
  getMsg:
    handler: service-1.handler.api
    events:
      - http:
          path: student # Path for this endpoint
          method: get # HTTP method for this endpoint
    package: # Optional deployment packaging configuration
      include: # Specify the directories and files which should be included in the deployment package for this specific function.
        - service-1/**
        - service-1/handler.js
      exclude: 
        - service-2/**  
      individually: true    
  putMsg:
    handler: service-2.handler.api
    events:
      - http: 
          path: teacher # Path for this endpoint
          method: get # HTTP method for this endpoint
    package: # Optional deployment packaging configuration
      include: # Specify the directories and files which should be included in the deployment package for this specific function.
        - service-2/**
        - service-2/handler.js
      exclude: 
        - service-1/**   
      individually: true       
